import Head from "next/head"
import { getPosts } from "../utils/wordpress"
import Post from "../components/Post"

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>DKIP Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <h1 className="text-center">DKIP Next</h1>

          <div>
            <h2 className="">Berita</h2>

            <div className="row">
              {posts.map((post) => {
                return (
                  <div className="col-md-6 col-lg-4" key={post.id}>
                    <Post post={post} />
                  </div>
                )
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const posts = await getPosts()

  return {
    props: {
      posts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  }
}
